//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidIdv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int VisitorId { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> DateofVisit { get; set; }
        public string Department { get; set; }
        public string PurposeofVisit { get; set; }
        public string ValidID { get; set; }
        public string Selfie { get; set; }
        public string QRCode { get; set; }
    }
}
